//
//  Move.m
//  kickboxing app
//
//  Created by Bader on 5/19/20.
//  Copyright © 2020 Nebo. All rights reserved.
//

#import "Move.h"

@implementation Move
//auto generated by compiler
-(id)init: (NSString *) name : (Stance) take_off : (Stance) landing {
    self = [super init];
    if(self) {
        self.isActive = TRUE;
        self.name = name;
        self.take_off_stance = take_off;
        self.landing_stance = landing;
    }
    return self;
}

@end
